

"""
Synaptic weight evolution plot for neuromorphic simulation.

Reads data/raw/weights.csv (generated by the Rust core with STDP enabled)
and produces a plot showing how synaptic weights evolve over time.
"""
from analysis_utils import use_sf_fonts
use_sf_fonts()

from pathlib import Path
import csv
import matplotlib.pyplot as plt
from collections import defaultdict

# Resolve project root
PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_PATH = PROJECT_ROOT / "data" / "raw" / "weights.csv"
RESULTS_DIR = PROJECT_ROOT / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = RESULTS_DIR / "weight_evolution.png"

if not DATA_PATH.exists():
    raise FileNotFoundError(f"weights.csv not found at {DATA_PATH}")

# Load weights grouped by synapse (pre, post)
weights_by_synapse = defaultdict(list)

with open(DATA_PATH, "r", newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        t = float(row["time_ms"])
        pre = int(row["pre_neuron"])
        post = int(row["post_neuron"])
        w = float(row["weight"])
        weights_by_synapse[(pre, post)].append((t, w))

# Plot weight evolution
plt.figure(figsize=(9, 5))

for (pre, post), history in weights_by_synapse.items():
    times = [x[0] for x in history]
    weights = [x[1] for x in history]
    plt.plot(times, weights, linewidth=1, alpha=0.8, label=f"{pre}→{post}")

plt.xlabel("Time (ms)")
plt.ylabel("Synaptic Weight")
plt.title("Synaptic Weight Evolution (STDP)")
plt.grid(alpha=0.3)
plt.tight_layout()

# Legend only if small network
if len(weights_by_synapse) <= 10:
    plt.legend(fontsize=8)

plt.savefig(OUTPUT_PATH, dpi=300)
plt.savefig(OUTPUT_PATH.with_suffix(".svg"))
plt.close()

print(f"Saved weight evolution plot to: {OUTPUT_PATH}")