"""
Spike raster plot for neuromorphic simulation.

Reads spike events from data/raw/spikes.csv (generated by the Rust core)
and produces a raster plot saved to results/spike_raster.png.
"""
from analysis_utils import use_sf_fonts
use_sf_fonts()

from pathlib import Path
import csv
import matplotlib.pyplot as plt

# Resolve project root: neuromorphic-ai-paradigm/
PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_PATH = PROJECT_ROOT / "data" / "raw" / "spikes.csv"
RESULTS_DIR = PROJECT_ROOT / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = RESULTS_DIR / "spike_raster.png"

if not DATA_PATH.exists():
    raise FileNotFoundError(f"Spike CSV not found at {DATA_PATH}")

# Load spikes
times = []
neurons = []

with open(DATA_PATH, "r", newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        neurons.append(int(row["neuron_id"]))
        times.append(float(row["time_ms"]))

# Plot raster
plt.figure(figsize=(9, 4))
plt.scatter(times, neurons, s=14, marker="|", color="black")
plt.xlabel("Time (ms)")
plt.ylabel("Neuron Index")
plt.title("Spike Raster Plot (Spiking Neural Network)")
plt.yticks(sorted(set(neurons)))
plt.grid(axis="x", linestyle="--", alpha=0.3)
plt.tight_layout()

# Save figure
plt.savefig(OUTPUT_PATH, dpi=300)
plt.savefig(OUTPUT_PATH.with_suffix(".svg"))
plt.close()
print(f"Saved spike raster to: {OUTPUT_PATH} and SVG variant")
